version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: idna
    versions:
    - "3.1"
- package-ecosystem: npm
  directory: "/static"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: react-popper
    versions:
    - 2.2.5
  - dependency-name: web-vitals
    versions:
    - 1.1.1
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.1
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
