# This workflow will install Python dependencies, lint, and check code style

name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8==3.9.1 pylint==2.7.4 black==20.8b1 isort==5.8.0
    - name: Run checks
      run: |
        # Python code formatter:
        black --check .
        # Check if imports are sorted alphabetically and automatically separated into sections and by type:
        isort --check --profile black .
        # Python static code analysis:
        pylint . --disable=W0511,W0105,C0103 --max-line-length=127
        # Stop the build if there are Python syntax errors or undefined names:
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide:
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
